name: Lint checker
on: push

jobs:
  testLint:
    name: Test Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: HUSKY=0 npm ci && npm i prettier eslint -g
      - name: Check Lint
        run: npm run checklint